// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkyBooker.FlightService.Data;

#nullable disable

namespace SkyBooker.FlightService.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20260515185859_InitialPostgresCreate")]
    partial class InitialPostgresCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkyBooker.FlightService.Models.Airline", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AirlineId"));

                    b.Property<string>("AirlineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IATACode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ICAOCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("AirlineId");

                    b.HasIndex("IATACode")
                        .IsUnique()
                        .HasDatabaseName("IX_Airline_IATACode");

                    b.ToTable("Airlines", (string)null);

                    b.HasData(
                        new
                        {
                            AirlineId = 1,
                            AirlineName = "Air India",
                            Country = "India",
                            IATACode = "AI",
                            ICAOCode = "AIC",
                            IsActive = true
                        },
                        new
                        {
                            AirlineId = 2,
                            AirlineName = "IndiGo",
                            Country = "India",
                            IATACode = "6E",
                            ICAOCode = "IGO",
                            IsActive = true
                        },
                        new
                        {
                            AirlineId = 3,
                            AirlineName = "SpiceJet",
                            Country = "India",
                            IATACode = "SG",
                            ICAOCode = "SEJ",
                            IsActive = true
                        },
                        new
                        {
                            AirlineId = 4,
                            AirlineName = "Vistara",
                            Country = "India",
                            IATACode = "UK",
                            ICAOCode = "VTI",
                            IsActive = true
                        },
                        new
                        {
                            AirlineId = 5,
                            AirlineName = "AirAsia India",
                            Country = "India",
                            IATACode = "I5",
                            ICAOCode = "IAD",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SkyBooker.FlightService.Models.Airport", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AirportId"));

                    b.Property<string>("AirportName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IATACode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ICAOCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Timezone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("AirportId");

                    b.HasIndex("IATACode")
                        .IsUnique()
                        .HasDatabaseName("IX_Airport_IATACode");

                    b.ToTable("Airports", (string)null);

                    b.HasData(
                        new
                        {
                            AirportId = 1,
                            AirportName = "Indira Gandhi International Airport",
                            City = "New Delhi",
                            Country = "India",
                            IATACode = "DEL",
                            ICAOCode = "VIDP",
                            Latitude = 28.5665m,
                            Longitude = 77.1031m,
                            Timezone = "Asia/Kolkata"
                        },
                        new
                        {
                            AirportId = 2,
                            AirportName = "Chhatrapati Shivaji Maharaj International Airport",
                            City = "Mumbai",
                            Country = "India",
                            IATACode = "BOM",
                            ICAOCode = "VABB",
                            Latitude = 19.0896m,
                            Longitude = 72.8656m,
                            Timezone = "Asia/Kolkata"
                        },
                        new
                        {
                            AirportId = 3,
                            AirportName = "Kempegowda International Airport",
                            City = "Bangalore",
                            Country = "India",
                            IATACode = "BLR",
                            ICAOCode = "VOBL",
                            Latitude = 13.1986m,
                            Longitude = 77.7066m,
                            Timezone = "Asia/Kolkata"
                        },
                        new
                        {
                            AirportId = 4,
                            AirportName = "Chennai International Airport",
                            City = "Chennai",
                            Country = "India",
                            IATACode = "MAA",
                            ICAOCode = "VOMM",
                            Latitude = 12.9941m,
                            Longitude = 80.1709m,
                            Timezone = "Asia/Kolkata"
                        },
                        new
                        {
                            AirportId = 5,
                            AirportName = "Netaji Subhas Chandra Bose International Airport",
                            City = "Kolkata",
                            Country = "India",
                            IATACode = "CCU",
                            ICAOCode = "VECC",
                            Latitude = 22.6547m,
                            Longitude = 88.4467m,
                            Timezone = "Asia/Kolkata"
                        },
                        new
                        {
                            AirportId = 6,
                            AirportName = "Rajiv Gandhi International Airport",
                            City = "Hyderabad",
                            Country = "India",
                            IATACode = "HYD",
                            ICAOCode = "VOHS",
                            Latitude = 17.2403m,
                            Longitude = 78.4294m,
                            Timezone = "Asia/Kolkata"
                        },
                        new
                        {
                            AirportId = 7,
                            AirportName = "Pune Airport",
                            City = "Pune",
                            Country = "India",
                            IATACode = "PNQ",
                            ICAOCode = "VAPO",
                            Latitude = 18.5822m,
                            Longitude = 73.9197m,
                            Timezone = "Asia/Kolkata"
                        },
                        new
                        {
                            AirportId = 8,
                            AirportName = "Sardar Vallabhbhai Patel International Airport",
                            City = "Ahmedabad",
                            Country = "India",
                            IATACode = "AMD",
                            ICAOCode = "VAAH",
                            Latitude = 23.0772m,
                            Longitude = 72.6347m,
                            Timezone = "Asia/Kolkata"
                        });
                });

            modelBuilder.Entity("SkyBooker.FlightService.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FlightId"));

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("AirlineId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("integer");

                    b.Property<decimal>("BusinessPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationAirportCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("EconomyPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OriginAirportCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineId")
                        .HasDatabaseName("IX_Flight_AirlineId");

                    b.HasIndex("FlightNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Flight_FlightNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Flight_Status");

                    b.HasIndex("OriginAirportCode", "DestinationAirportCode", "DepartureTime")
                        .HasDatabaseName("IX_Flight_Route_DateTime");

                    b.ToTable("Flights", (string)null);

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            AircraftType = "Boeing 787",
                            AirlineId = 1,
                            ArrivalTime = new DateTime(2026, 5, 14, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 180,
                            BusinessPrice = 8500.00m,
                            CreatedAt = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 14, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirportCode = "BOM",
                            DurationMinutes = 150,
                            EconomyPrice = 5500.00m,
                            FlightNumber = "AI101",
                            OriginAirportCode = "DEL",
                            Status = 0,
                            TotalSeats = 250
                        },
                        new
                        {
                            FlightId = 2,
                            AircraftType = "Airbus A320",
                            AirlineId = 2,
                            ArrivalTime = new DateTime(2026, 5, 14, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 120,
                            BusinessPrice = 6200.00m,
                            CreatedAt = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirportCode = "BLR",
                            DurationMinutes = 105,
                            EconomyPrice = 4200.00m,
                            FlightNumber = "6E202",
                            OriginAirportCode = "BOM",
                            Status = 0,
                            TotalSeats = 180
                        },
                        new
                        {
                            FlightId = 3,
                            AircraftType = "Airbus A321",
                            AirlineId = 4,
                            ArrivalTime = new DateTime(2026, 5, 14, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 45,
                            BusinessPrice = 9200.00m,
                            CreatedAt = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 14, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirportCode = "BOM",
                            DurationMinutes = 150,
                            EconomyPrice = 6200.00m,
                            FlightNumber = "UK303",
                            OriginAirportCode = "DEL",
                            Status = 0,
                            TotalSeats = 200
                        },
                        new
                        {
                            FlightId = 4,
                            AircraftType = "Boeing 737",
                            AirlineId = 3,
                            ArrivalTime = new DateTime(2026, 5, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 90,
                            BusinessPrice = 7200.00m,
                            CreatedAt = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 15, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirportCode = "BOM",
                            DurationMinutes = 150,
                            EconomyPrice = 4800.00m,
                            FlightNumber = "SG404",
                            OriginAirportCode = "DEL",
                            Status = 0,
                            TotalSeats = 180
                        },
                        new
                        {
                            FlightId = 5,
                            AircraftType = "Boeing 787",
                            AirlineId = 1,
                            ArrivalTime = new DateTime(2026, 5, 14, 23, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 200,
                            BusinessPrice = 8200.00m,
                            CreatedAt = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 14, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationAirportCode = "DEL",
                            DurationMinutes = 150,
                            EconomyPrice = 5200.00m,
                            FlightNumber = "AI102",
                            OriginAirportCode = "BOM",
                            Status = 0,
                            TotalSeats = 250
                        });
                });

            modelBuilder.Entity("SkyBooker.FlightService.Models.Flight", b =>
                {
                    b.HasOne("SkyBooker.FlightService.Models.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("SkyBooker.FlightService.Models.Airline", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
